services:
  - type: web
    name: pub-9router-cloud
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
      - key: INITIAL_PASSWORD
        value: pubdevloop2026
